server:
  port: 8101

spring:
  application:
    name: mi-auth
  profiles:
    active: dev


eureka:
  instance:
    lease-renewal-interval-in-seconds: 20 #向Eureka 服务端发送心跳的间隔时间，单位为秒，用于服务续约
    hostname: mi-auth
    instance-id: mi-auth
  client:
    service-url:
      defaultZone: http://127.0.0.1:8001/eureka/
    register-with-eureka: true #为true时表示将当前服务注册到Eureak服务端
    fetch-registry: true #为true时表示从Eureka 服务端获取注册的服务信息
    instance-info-replication-interval-seconds: 30 #新实例信息的变化到Eureka服务端的间隔时间，单位为秒
    registry-fetch-interval-seconds: 3 #默认值为30秒，即每30秒去Eureka服务端上获取服务并缓存，这里指定为3秒的原因是方便开发时测试，实际可以指定为默认值即可