spring:
  application:
    name: mi-order-api
  profiles:
    active: dev
  redis:
    timeout: 10000
    host: 127.0.0.1
    port: 6379
    password:
    database: 1
    lettuce:
      pool:
        max-active: 8
        max-wait: 10000
        max-idle: 8
        min-idle: 5